### ISSUE TITLE
FEATURE REQUEST: Add option to replicate.sh to not auto-restart databases after replicate.

### ISSUE THREAD

**Issue by scosol** [Appdynamics/HA-toolkit#86]
Use model: customer has "master controller" kind of daemon-servicing infrastructure in place across all systems-
They wish to use it to monitor and control all starts and stops of the services.
The replicate.sh script has an option to disable appserver startup but not db startup.
They want to create their own "jobs" that run replicate, start and stop the db and appserver etc, but they need all the starting-and-stopping parts of replicate.sh able to be defeated via cmdline options.

**Comment by cmayer68** [comment]
this is strange enough that I'm going to tell them to fork the HA toolkit.  the need to restart the database is not just as a convenience, but that we need to start both databases in order to add the replication user, add the grants, and set up the replication slave.  so what they are really asking for is an additional shutdown after replicate runs.  this is bizarre, and does not fit any use case that I can see.
