### ISSUE TITLE
Missing line continuation, premature glob expansion in replicate.sh

### ISSUE THREAD

**Issue by mprzybylski** [Appdynamics/HA-toolkit#89]
Lines 740 through 743 of https://github.com/Appdynamics/HA-toolkit/blob/2b4474658145c08617e0363be628925790c95180/replicate.sh :
```
	$SSH $secondary rm -f $APPD_ROOT/bin/controller.sh \
		"$innodb_logdir/ib_logfile*"
		"$datadir/*log*" \
		$datadir/ibdata1 2>&1 | logonly
```

There is a missing `\` on line 741, so `"$datadir/*log*"...` gets interpreted as a command rather than arguments to `ssh ... rm -f ...`.

Also, the `*` characters should be preceded by a `\` character so that the filename globs they belong to will be expanded on `$secondary` rather than locally

**Comment by cmayer68** [comment]
nice.   fixed in 3.40, pushed now.

--curt

On Mon, Aug 27, 2018 at 12:51 PM Mike Przybylski <notifications@github.com>
wrote:

> Assigned #89
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Appdynamics_HA-2Dtoolkit_issues_89&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=nsJ1Vt4kkj1MF7fPuYx_OHpUcucCi7WPVJJQ5IIS6oA&m=IEAFQ3m1bbxFXsO5fnNmUssKn3AmN0k6EaF_CG-4W3Y&s=1xkaXO0I0F-FpY_m1vxNv3uKTaxtdtg5TKol0q_dL18&e=>
> to @cmayer68
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cmayer68&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=nsJ1Vt4kkj1MF7fPuYx_OHpUcucCi7WPVJJQ5IIS6oA&m=IEAFQ3m1bbxFXsO5fnNmUssKn3AmN0k6EaF_CG-4W3Y&s=zSVF5JonZwqrpK0xrBFZe9q3oNoAxpPcOJfmKayJJIs&e=>
> .
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Appdynamics_HA-2Dtoolkit_issues_89-23event-2D1811449588&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=nsJ1Vt4kkj1MF7fPuYx_OHpUcucCi7WPVJJQ5IIS6oA&m=IEAFQ3m1bbxFXsO5fnNmUssKn3AmN0k6EaF_CG-4W3Y&s=V5jRmETEQY2Y_cZesmS4U0OhgWCVjikoZ7AqHTbePiI&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_APNeTI9WQC3Sv6Gu0-2DHUaFeHnhv01RcDks5uVE3EgaJpZM4WOWI8&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=nsJ1Vt4kkj1MF7fPuYx_OHpUcucCi7WPVJJQ5IIS6oA&m=IEAFQ3m1bbxFXsO5fnNmUssKn3AmN0k6EaF_CG-4W3Y&s=445osu8XdsTM2LLvBpsIT4HrSz-SuQZY9tgVuHIK6nw&e=>
> .
>


-- 
*Curt Mayer* | Senior Architect, Customer Success
Office 707.540.3441 | Mobile 707.540.3441
<http://appdynamics.com/>
Watch  <http://appdynamics.wistia.com/medias/56gnkuk6mv>our Video | Try
<https://portal.appdynamics.com/account/signup/signupForm>our FREE Trial |
Twitter  <http://www.twitter.com/appdynamics>| Facebook
<http://www.facebook.com/pages/AppDynamics/193264136815?ref=nf>|
appdynamics.com <http://www.appdynamics.com/>
